version: "3.8"

services:
  frontend:
    build:
      context: ./numida
      dockerfile: Dockerfile
    ports:
      - "19000:19000" # Expo Metro Bundler
      - "19001:19001" # Expo DevTools
      - "19002:19002" # Expo Packager
    networks:
      - app-network
    command: yarn start --host lan
    volumes:
      - ./numida:/app # For live reloading during development

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Flask backend server
    networks:
      - app-network
    volumes:
      - ./server:/app # For live reloading during development

networks:
  app-network:
    driver: bridge
